swagger: '2.0'
info:
  version: '1.0.0'
  title: assistant-cloudant
# basePath prefixes all resource paths
basePath: /api
#
schemes:
# tip: remove http to make production-grade
- http
- https

# format of bodies a client can send (Content-Type)
consumes:
- application/json

# format of the responses to the client (Accepts)
produces:
- application/json
- text/plain

tags:
- name: assistant
  description: assistant apis
- name: cloudant
  description: cloudant apis

paths:
  /swagger:
    x-swagger-pipe: swagger_raw

  /assistant:
    # binds app logic to a route
    x-swagger-router-controller: assistant
    post:
      tags:
      - assistant
      description: returns a number
      # used as the method name of the controller
      operationId: message
      parameters:
      - name: body
        in: body
        description: 'message to assistant'
        schema:
          $ref: '#/definitions/Message'
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: '#/definitions/Assistant'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'

  /cloudant/{id}:
    # binds app logic to a route
    x-swagger-router-controller: cloudant
    get:
      tags:
      - cloudant
      description: use this to retrieve a document from cloudant
      # used as the method name of the controller
      operationId: get
      parameters:
      - name: id
        in: path
        required: true
        description: 'document id'
        type: string
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: '#/definitions/CloudantDoc'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'

  /cloudant:
    # binds app logic to a route
    x-swagger-router-controller: cloudant
    put:
      tags:
      - cloudant
      description: use this to put a document in cloudant
      # used as the method name of the controller
      operationId: put
      parameters:
      - name: body
        in: body
        description: 'document'
        schema:
          $ref: '#/definitions/CloudantDoc'
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: '#/definitions/CloudantDoc'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'

# complex objects have schema definitions
definitions:
  Message:
    type: object
    required:
    - text
    properties:
      text:
        type: string
    example:
      text: 'ciao watson, come stai?'

  Assistant:
    type: object

  CloudantDoc:
    type: object
    properties:
      _id:
        type: string
      _rev:
        type: string

  Success:
    type: object
    required:
    - message
    properties:
      message:
        type: string

  Error:
    type: object
    required:
    - error
    - message
    properties:
      error:
        type: boolean
      message:
        type: string
